service: tokens

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  tokens-get:
    handler: src/handlers/obtener-datos-tarjeta.handler
    events:
      - httpApi: GET /tokens

  tokens-post:
    handler: src/handlers/crear-token.handler
    events:
      - httpApi: POST /tokens

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline